version: "3.5"

services:
  mysql:
    image: mysql:5
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: definitions
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    healthcheck: # This is actually not needed. Apps should have their own resiliency.
      test: ["CMD-SHELL", "mysql -ptest123 -e 'select 1'"]
      interval: 5s
      retries: 50

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
  api:
    image: node:latest
    volumes:
      - ./application/server:/server
    ports:
      - 81:81
    command: "yarn --cwd /server start"